"""
Scraper ASJP — Version corrigée avec 888 URLs directes
SSL verify désactivé car certificat ASJP expiré
Limité à 20 revues pour respecter la mémoire du plan gratuit Render
"""
import re
import logging
import time
import urllib3
from datetime import datetime, date
from typing import List, Dict, Optional
import requests
from bs4 import BeautifulSoup
from app.scrapers.base import BaseScraper

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

logger = logging.getLogger(__name__)

REVUES_ASJP = [
    {"name": "AGROBIOLOGIA", "url": "https://asjp.cerist.dz/en/PresentationRevue/255"},
    {"name": "AL-Lisaniyyat", "url": "https://asjp.cerist.dz/en/PresentationRevue/26"},
    {"name": "AL-MUTARĞIM المترجم", "url": "https://asjp.cerist.dz/en/PresentationRevue/33"},
    {"name": "ALTRALANG Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/597"},
    {"name": "Academia", "url": "https://asjp.cerist.dz/en/PresentationRevue/522"},
    {"name": "Action didactique", "url": "https://asjp.cerist.dz/en/PresentationRevue/843"},
    {"name": "Advanced Research in Economics and Business Strategy Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/757"},
    {"name": "Africa", "url": "https://asjp.cerist.dz/en/PresentationRevue/1005"},
    {"name": "Africa and the West", "url": "https://asjp.cerist.dz/en/PresentationRevue/156"},
    {"name": "Agriculture", "url": "https://asjp.cerist.dz/en/PresentationRevue/53"},
    {"name": "Agropastoralis Scientia", "url": "https://asjp.cerist.dz/en/PresentationRevue/960"},
    {"name": "Al Athar مجلة الأثـــــــــــــــر", "url": "https://asjp.cerist.dz/en/PresentationRevue/24"},
    {"name": "Aleph", "url": "https://asjp.cerist.dz/en/PresentationRevue/226"},
    {"name": "Algerian Annals of Agronomy", "url": "https://asjp.cerist.dz/en/PresentationRevue/12"},
    {"name": "Algerian Journal of Arid Environment “AJAE”", "url": "https://asjp.cerist.dz/en/PresentationRevue/11"},
    {"name": "Algerian Journal of Biosciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/754"},
    {"name": "Algerian Journal of Electrical Systems and Sustainability", "url": "https://asjp.cerist.dz/en/PresentationRevue/1007"},
    {"name": "Algerian Journal of Engineering Research", "url": "https://asjp.cerist.dz/en/PresentationRevue/578"},
    {"name": "Algerian Journal of Engineering and Technology", "url": "https://asjp.cerist.dz/en/PresentationRevue/732"},
    {"name": "Algerian Journal of Forensic Sciences and Criminology", "url": "https://asjp.cerist.dz/en/PresentationRevue/949"},
    {"name": "Algerian Journal of Health Sciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/689"},
    {"name": "Algerian Journal of Human and Social Sciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/579"},
    {"name": "Algerian Journal of Management Sciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/847"},
    {"name": "Algerian Journal of Materials Chemistry", "url": "https://asjp.cerist.dz/en/PresentationRevue/637"},
    {"name": "Algerian Journal of Natural Products", "url": "https://asjp.cerist.dz/en/PresentationRevue/59"},
    {"name": "Algerian Journal of Pharmaceutical Engineering", "url": "https://asjp.cerist.dz/en/PresentationRevue/922"},
    {"name": "Algerian Journal of Renewable Energy and Sustainable Development", "url": "https://asjp.cerist.dz/en/PresentationRevue/736"},
    {"name": "Algerian Journal of Research and Technology", "url": "https://asjp.cerist.dz/en/PresentationRevue/538"},
    {"name": "Algerian Journal of Sciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/969"},
    {"name": "Algerian Journal of Signals and Systems", "url": "https://asjp.cerist.dz/en/PresentationRevue/420"},
    {"name": "Algerian Review of Ottoman and Mediterranean Studies", "url": "https://asjp.cerist.dz/en/PresentationRevue/853"},
    {"name": "Algerian journal of economic performance", "url": "https://asjp.cerist.dz/en/PresentationRevue/842"},
    {"name": "Annales de la Recherche Forestière en Algérie", "url": "https://asjp.cerist.dz/en/PresentationRevue/592"},
    {"name": "Annales de l’université d’Alger", "url": "https://asjp.cerist.dz/en/PresentationRevue/18"},
    {"name": "Annales du Musée National des Antiquités", "url": "https://asjp.cerist.dz/en/PresentationRevue/987"},
    {"name": "Annales du patrimoine", "url": "https://asjp.cerist.dz/en/PresentationRevue/366"},
    {"name": "Applied Biology in Saharan Areas", "url": "https://asjp.cerist.dz/en/PresentationRevue/554"},
    {"name": "Batna Journal of Medical Sciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/706"},
    {"name": "Biocenoses", "url": "https://asjp.cerist.dz/en/PresentationRevue/43"},
    {"name": "Biopolymer Applications Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/975"},
    {"name": "Bulletin des sciences géographiques de l\'INCT", "url": "https://asjp.cerist.dz/en/PresentationRevue/213"},
    {"name": "Bulletin du Service Géologique de l\'Algérie", "url": "https://asjp.cerist.dz/en/PresentationRevue/6"},
    {"name": "Cahiers Géographiques de l’Ouest", "url": "https://asjp.cerist.dz/en/PresentationRevue/953"},
    {"name": "Cahiers de Recherches en Sciences du Langage", "url": "https://asjp.cerist.dz/en/PresentationRevue/921"},
    {"name": "Cahiers de Traduction", "url": "https://asjp.cerist.dz/en/PresentationRevue/224"},
    {"name": "Cahiers de sociologie", "url": "https://asjp.cerist.dz/en/PresentationRevue/358"},
    {"name": "Com-Santé", "url": "https://asjp.cerist.dz/en/PresentationRevue/942"},
    {"name": "Communication science et technologie", "url": "https://asjp.cerist.dz/en/PresentationRevue/42"},
    {"name": "Contextes Didactiques, Linguistiques et Culturels", "url": "https://asjp.cerist.dz/en/PresentationRevue/928"},
    {"name": "Courrier du Savoir scientifique et technique", "url": "https://asjp.cerist.dz/en/PresentationRevue/128"},
    {"name": "DIDACSTYLE", "url": "https://asjp.cerist.dz/en/PresentationRevue/385"},
    {"name": "DIDASKEIN", "url": "https://asjp.cerist.dz/en/PresentationRevue/752"},
    {"name": "Didactiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/300"},
    {"name": "Dirassat", "url": "https://asjp.cerist.dz/en/PresentationRevue/60"},
    {"name": "ENP Engineering Science Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/931"},
    {"name": "Eddissi Languages Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/857"},
    {"name": "Educ recherche", "url": "https://asjp.cerist.dz/en/PresentationRevue/573"},
    {"name": "El-Tawassol التواصل", "url": "https://asjp.cerist.dz/en/PresentationRevue/27"},
    {"name": "El-paradigm Journal مجلة البراديغم", "url": "https://asjp.cerist.dz/en/PresentationRevue/577"},
    {"name": "Ex Professo", "url": "https://asjp.cerist.dz/en/PresentationRevue/484"},
    {"name": "Expressions", "url": "https://asjp.cerist.dz/en/PresentationRevue/51"},
    {"name": "Expériences pédagogiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/891"},
    {"name": "FORUM DE L\' ENSEIGNANT منتدى الأستاذ", "url": "https://asjp.cerist.dz/en/PresentationRevue/80"},
    {"name": "Fabriques Urbaines", "url": "https://asjp.cerist.dz/en/PresentationRevue/945"},
    {"name": "Genetics and Biodiversity Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/398"},
    {"name": "Hippocampus", "url": "https://asjp.cerist.dz/en/PresentationRevue/850"},
    {"name": "Hispanical", "url": "https://asjp.cerist.dz/en/PresentationRevue/831"},
    {"name": "IMAGO Interculturalité et Didactique", "url": "https://asjp.cerist.dz/en/PresentationRevue/543"},
    {"name": "Iles d Imesli", "url": "https://asjp.cerist.dz/en/PresentationRevue/397"},
    {"name": "Insaniyat", "url": "https://asjp.cerist.dz/en/PresentationRevue/14"},
    {"name": "International Journal of Automation and Safety", "url": "https://asjp.cerist.dz/en/PresentationRevue/944"},
    {"name": "International Journal of Chemical and Petroleum Sciences (IJCPS)", "url": "https://asjp.cerist.dz/en/PresentationRevue/118"},
    {"name": "International Journal of Natural Resources and Environment", "url": "https://asjp.cerist.dz/en/PresentationRevue/863"},
    {"name": "International journal of electronic and electrical engineering systems", "url": "https://asjp.cerist.dz/en/PresentationRevue/517"},
    {"name": "JEFIS", "url": "https://asjp.cerist.dz/en/PresentationRevue/729"},
    {"name": "JOURNAL ALGÉRIEN DE PHARMACIE", "url": "https://asjp.cerist.dz/en/PresentationRevue/436"},
    {"name": "JOURNAL DE NEUROCHIRURGIE", "url": "https://asjp.cerist.dz/en/PresentationRevue/421"},
    {"name": "JOURNAL OF FINANCE & CORPORATE GOVERNANCE", "url": "https://asjp.cerist.dz/en/PresentationRevue/464"},
    {"name": "JOURNAL OF MANAGEMENT & ORGANIZATIONAL DYNAMICS", "url": "https://asjp.cerist.dz/en/PresentationRevue/965"},
    {"name": "JOURNAL OF RENEWABLE ENERGY SYSTEMS AND MANAGEMENT", "url": "https://asjp.cerist.dz/en/PresentationRevue/992"},
    {"name": "Journal Algérien des Régions Arides", "url": "https://asjp.cerist.dz/en/PresentationRevue/102"},
    {"name": "Journal Of Work And Entreprenuiship Research", "url": "https://asjp.cerist.dz/en/PresentationRevue/1010"},
    {"name": "Journal algérien de biochimie et de génétique médicales", "url": "https://asjp.cerist.dz/en/PresentationRevue/815"},
    {"name": "Journal de la Faculté de Médecine", "url": "https://asjp.cerist.dz/en/PresentationRevue/589"},
    {"name": "Journal of Advanced Research in Science and Technology", "url": "https://asjp.cerist.dz/en/PresentationRevue/112"},
    {"name": "Journal of Applied Engineering Science & Technology", "url": "https://asjp.cerist.dz/en/PresentationRevue/115"},
    {"name": "Journal of Building Materials and Structures", "url": "https://asjp.cerist.dz/en/PresentationRevue/292"},
    {"name": "Journal of Economic Geography", "url": "https://asjp.cerist.dz/en/PresentationRevue/971"},
    {"name": "Journal of Economics and Rural Development", "url": "https://asjp.cerist.dz/en/PresentationRevue/958"},
    {"name": "Journal of Languages and Translation", "url": "https://asjp.cerist.dz/en/PresentationRevue/710"},
    {"name": "Journal of Management and Organizations Strategy", "url": "https://asjp.cerist.dz/en/PresentationRevue/870"},
    {"name": "Journal of Materials and Engineering Structures", "url": "https://asjp.cerist.dz/en/PresentationRevue/246"},
    {"name": "Journal of Materials, Processes and Environment", "url": "https://asjp.cerist.dz/en/PresentationRevue/284"},
    {"name": "Journal of Molecular and Pharmaceutical Sciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/859"},
    {"name": "Journal of New Technology and Materials", "url": "https://asjp.cerist.dz/en/PresentationRevue/36"},
    {"name": "Journal of Private Law", "url": "https://asjp.cerist.dz/en/PresentationRevue/954"},
    {"name": "Journal of Scientific Research", "url": "https://asjp.cerist.dz/en/PresentationRevue/193"},
    {"name": "Journal of Studies in Language, Culture and Society (JSLCS)", "url": "https://asjp.cerist.dz/en/PresentationRevue/681"},
    {"name": "Journal of innovative applied mathematics and computational sciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/869"},
    {"name": "Journal of social protection research", "url": "https://asjp.cerist.dz/en/PresentationRevue/703"},
    {"name": "L\'entreprise", "url": "https://asjp.cerist.dz/en/PresentationRevue/248"},
    {"name": "LANCOMNET", "url": "https://asjp.cerist.dz/en/PresentationRevue/425"},
    {"name": "LARHYSS Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/125"},
    {"name": "La Revue des Sciences Commerciales", "url": "https://asjp.cerist.dz/en/PresentationRevue/360"},
    {"name": "La revue de la Communication et du Journalisme", "url": "https://asjp.cerist.dz/en/PresentationRevue/290"},
    {"name": "La revue médicale de l\'HMRUO", "url": "https://asjp.cerist.dz/en/PresentationRevue/828"},
    {"name": "La revue regards sur le droit social", "url": "https://asjp.cerist.dz/en/PresentationRevue/159"},
    {"name": "Langues & Cultures", "url": "https://asjp.cerist.dz/en/PresentationRevue/625"},
    {"name": "Langues & Usages", "url": "https://asjp.cerist.dz/en/PresentationRevue/618"},
    {"name": "Langues, discours et inter cultures", "url": "https://asjp.cerist.dz/en/PresentationRevue/766"},
    {"name": "Le Journal de l\'Eau et de l\'Environnement", "url": "https://asjp.cerist.dz/en/PresentationRevue/243"},
    {"name": "Le Manager", "url": "https://asjp.cerist.dz/en/PresentationRevue/451"},
    {"name": "Les Cahiers du SLADD", "url": "https://asjp.cerist.dz/en/PresentationRevue/569"},
    {"name": "Les cahiers du CREAD", "url": "https://asjp.cerist.dz/en/PresentationRevue/22"},
    {"name": "Les cahiers du LAPSI", "url": "https://asjp.cerist.dz/en/PresentationRevue/50"},
    {"name": "Management and social perspectives", "url": "https://asjp.cerist.dz/en/PresentationRevue/886"},
    {"name": "Marefa review", "url": "https://asjp.cerist.dz/en/PresentationRevue/247"},
    {"name": "Marketing and business research review", "url": "https://asjp.cerist.dz/en/PresentationRevue/790"},
    {"name": "Materials & biomaterials science", "url": "https://asjp.cerist.dz/en/PresentationRevue/660"},
    {"name": "Mediterranean Journal of Modeling and Simulation", "url": "https://asjp.cerist.dz/en/PresentationRevue/10"},
    {"name": "Models & Optimisation and Mathematical Analysis Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/40"},
    {"name": "Multilinguales", "url": "https://asjp.cerist.dz/en/PresentationRevue/13"},
    {"name": "Nutrition & Santé", "url": "https://asjp.cerist.dz/en/PresentationRevue/8"},
    {"name": "Oceanographia Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/984"},
    {"name": "PELAGOS", "url": "https://asjp.cerist.dz/en/PresentationRevue/913"},
    {"name": "Paradigmes", "url": "https://asjp.cerist.dz/en/PresentationRevue/646"},
    {"name": "Passerelle", "url": "https://asjp.cerist.dz/en/PresentationRevue/531"},
    {"name": "Passerelles", "url": "https://asjp.cerist.dz/en/PresentationRevue/691"},
    {"name": "PhytoChem & BioSub Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/322"},
    {"name": "Pratiques & didactique", "url": "https://asjp.cerist.dz/en/PresentationRevue/764"},
    {"name": "Process Engineering Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/74"},
    {"name": "Psychologie", "url": "https://asjp.cerist.dz/en/PresentationRevue/411"},
    {"name": "RECHERCHES", "url": "https://asjp.cerist.dz/en/PresentationRevue/251"},
    {"name": "REVUE ALGERIENNE DE FINANCES PUBLIQUES", "url": "https://asjp.cerist.dz/en/PresentationRevue/175"},
    {"name": "REVUE ALGERIENNE D’ALLERGOLOGIE", "url": "https://asjp.cerist.dz/en/PresentationRevue/588"},
    {"name": "REVUE SIENCES TECHNOLOGIES & DEVELOPPEMENT", "url": "https://asjp.cerist.dz/en/PresentationRevue/446"},
    {"name": "RIDILCA", "url": "https://asjp.cerist.dz/en/PresentationRevue/874"},
    {"name": "RIST", "url": "https://asjp.cerist.dz/en/PresentationRevue/134"},
    {"name": "Recherche Agronomique", "url": "https://asjp.cerist.dz/en/PresentationRevue/214"},
    {"name": "Recherches psychologiques et educatives", "url": "https://asjp.cerist.dz/en/PresentationRevue/55"},
    {"name": "Recueil de mécanique", "url": "https://asjp.cerist.dz/en/PresentationRevue/293"},
    {"name": "Revue Académique de la Recherche Juridique", "url": "https://asjp.cerist.dz/en/PresentationRevue/72"},
    {"name": "Revue Algérienne d\'Economie et de Management", "url": "https://asjp.cerist.dz/en/PresentationRevue/145"},
    {"name": "Revue Algérienne de la Communication", "url": "https://asjp.cerist.dz/en/PresentationRevue/437"},
    {"name": "Revue Algérienne des Etudes de Population", "url": "https://asjp.cerist.dz/en/PresentationRevue/422"},
    {"name": "Revue Algérienne des Maladies Respiratoires", "url": "https://asjp.cerist.dz/en/PresentationRevue/923"},
    {"name": "Revue Algérienne des Ressources Humaines", "url": "https://asjp.cerist.dz/en/PresentationRevue/139"},
    {"name": "Revue Algérienne des Sciences Juridiques et Politiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/32"},
    {"name": "Revue Algérienne des Sciences du Langage", "url": "https://asjp.cerist.dz/en/PresentationRevue/218"},
    {"name": "Revue Des Sciences Humaines", "url": "https://asjp.cerist.dz/en/PresentationRevue/23"},
    {"name": "Revue Etudes en Economie et Commerce et Finance", "url": "https://asjp.cerist.dz/en/PresentationRevue/263"},
    {"name": "Revue Finance & marchés", "url": "https://asjp.cerist.dz/en/PresentationRevue/329"},
    {"name": "Revue LAROS", "url": "https://asjp.cerist.dz/en/PresentationRevue/533"},
    {"name": "Revue Les Cahiers du POIDEX", "url": "https://asjp.cerist.dz/en/PresentationRevue/195"},
    {"name": "Revue Maghrébine Management des Organisations", "url": "https://asjp.cerist.dz/en/PresentationRevue/582"},
    {"name": "Revue Maghrébine des Langues", "url": "https://asjp.cerist.dz/en/PresentationRevue/163"},
    {"name": "Revue Médicale", "url": "https://asjp.cerist.dz/en/PresentationRevue/964"},
    {"name": "Revue Nature et Technologie", "url": "https://asjp.cerist.dz/en/PresentationRevue/47"},
    {"name": "Revue Organisation et Travail", "url": "https://asjp.cerist.dz/en/PresentationRevue/147"},
    {"name": "Revue Santé Mentale et Neurosciences", "url": "https://asjp.cerist.dz/en/PresentationRevue/889"},
    {"name": "Revue Scientifique Spécialisée des Sciences du Sport", "url": "https://asjp.cerist.dz/en/PresentationRevue/217"},
    {"name": "Revue algérienne d\'économie et gestion", "url": "https://asjp.cerist.dz/en/PresentationRevue/154"},
    {"name": "Revue algérienne des lettres", "url": "https://asjp.cerist.dz/en/PresentationRevue/523"},
    {"name": "Revue d\'Architecture", "url": "https://asjp.cerist.dz/en/PresentationRevue/819"},
    {"name": "Revue d\'ECONOMIE et de MANAGEMENT", "url": "https://asjp.cerist.dz/en/PresentationRevue/576"},
    {"name": "Revue d\'Etudes Sur l\'Algérie et le Monde", "url": "https://asjp.cerist.dz/en/PresentationRevue/373"},
    {"name": "Revue d\'économie et de statistique appliquée", "url": "https://asjp.cerist.dz/en/PresentationRevue/240"},
    {"name": "Revue d\'études sur les institutions et le développement", "url": "https://asjp.cerist.dz/en/PresentationRevue/340"},
    {"name": "Revue de Didactique, Linguistique et Traduction", "url": "https://asjp.cerist.dz/en/PresentationRevue/951"},
    {"name": "Revue de Recherches et Etudes Scientifiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/450"},
    {"name": "Revue de droit des transports et des activités portuaires", "url": "https://asjp.cerist.dz/en/PresentationRevue/164"},
    {"name": "Revue de l\'Algerian Petroleum Institute", "url": "https://asjp.cerist.dz/en/PresentationRevue/225"},
    {"name": "Revue des Economies financières bancaires et de management", "url": "https://asjp.cerist.dz/en/PresentationRevue/181"},
    {"name": "Revue des Etudes Economiques Approfondies", "url": "https://asjp.cerist.dz/en/PresentationRevue/542"},
    {"name": "Revue des Sciences Fondamentales Appliquées", "url": "https://asjp.cerist.dz/en/PresentationRevue/5"},
    {"name": "Revue des Sciences Humaines & Sociales", "url": "https://asjp.cerist.dz/en/PresentationRevue/39"},
    {"name": "Revue des Sciences Sociales", "url": "https://asjp.cerist.dz/en/PresentationRevue/566"},
    {"name": "Revue des Substances Naturelles et Innovation Thérapeutique", "url": "https://asjp.cerist.dz/en/PresentationRevue/149"},
    {"name": "Revue des matériaux et énergies renouvelables", "url": "https://asjp.cerist.dz/en/PresentationRevue/532"},
    {"name": "Revue des reformes Economique et intégration dans l’économie mondiale", "url": "https://asjp.cerist.dz/en/PresentationRevue/211"},
    {"name": "Revue des sciences commerciales et de gestion", "url": "https://asjp.cerist.dz/en/PresentationRevue/716"},
    {"name": "Revue des sciences et sciences de l’ingénieur", "url": "https://asjp.cerist.dz/en/PresentationRevue/303"},
    {"name": "Revue droit international et développement", "url": "https://asjp.cerist.dz/en/PresentationRevue/375"},
    {"name": "Revue du chercheur des sciences et techniques des activités physiques et sportives", "url": "https://asjp.cerist.dz/en/PresentationRevue/720"},
    {"name": "Revue d’Économie & de Gestion", "url": "https://asjp.cerist.dz/en/PresentationRevue/438"},
    {"name": "Revue d’études archéologiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/210"},
    {"name": "Revue internationale de Traduction Moderne", "url": "https://asjp.cerist.dz/en/PresentationRevue/571"},
    {"name": "Revue plurilingue, Etudes des langues, littératures et cultures", "url": "https://asjp.cerist.dz/en/PresentationRevue/574"},
    {"name": "Revue tadamsa d\'unegmu", "url": "https://asjp.cerist.dz/en/PresentationRevue/795"},
    {"name": "Rеvuе des Energies Renouvelables", "url": "https://asjp.cerist.dz/en/PresentationRevue/401"},
    {"name": "SCIENCES DE L’HOMME", "url": "https://asjp.cerist.dz/en/PresentationRevue/415"},
    {"name": "SEMIOTICA", "url": "https://asjp.cerist.dz/en/PresentationRevue/994"},
    {"name": "SOCLES", "url": "https://asjp.cerist.dz/en/PresentationRevue/25"},
    {"name": "STRATEGIA", "url": "https://asjp.cerist.dz/en/PresentationRevue/254"},
    {"name": "Sciences & Technologie", "url": "https://asjp.cerist.dz/en/PresentationRevue/15"},
    {"name": "Sciences & technologie. A, sciences exactes", "url": "https://asjp.cerist.dz/en/PresentationRevue/406"},
    {"name": "Sciences & technologie. B, Sciences de l’ingénieur", "url": "https://asjp.cerist.dz/en/PresentationRevue/407"},
    {"name": "Sciences & technologie. C, Biotechnologies", "url": "https://asjp.cerist.dz/en/PresentationRevue/408"},
    {"name": "Sciences & technologie. D, Sciences de la terre", "url": "https://asjp.cerist.dz/en/PresentationRevue/409"},
    {"name": "Sciences et Pratiques des Activités Physiques Sportives et Artistiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/261"},
    {"name": "Sciences of sport performance", "url": "https://asjp.cerist.dz/en/PresentationRevue/772"},
    {"name": "Security & strategic affairs", "url": "https://asjp.cerist.dz/en/PresentationRevue/946"},
    {"name": "Studies in Linguistics and Language Education", "url": "https://asjp.cerist.dz/en/PresentationRevue/1009"},
    {"name": "Synthèse", "url": "https://asjp.cerist.dz/en/PresentationRevue/34"},
    {"name": "Systèmes Agraires et Environnement", "url": "https://asjp.cerist.dz/en/PresentationRevue/453"},
    {"name": "Séminaire Mathématique de Béjaia", "url": "https://asjp.cerist.dz/en/PresentationRevue/755"},
    {"name": "THE ALGERIAN HEART RHYTHM JOURNAL", "url": "https://asjp.cerist.dz/en/PresentationRevue/943"},
    {"name": "The Algerian Cardiac Surgeon", "url": "https://asjp.cerist.dz/en/PresentationRevue/990"},
    {"name": "The Cradle of Languages مهد اللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/601"},
    {"name": "The International Journal in Economics and Business Strategies", "url": "https://asjp.cerist.dz/en/PresentationRevue/918"},
    {"name": "The North African Journal of Food and Nutrition Research", "url": "https://asjp.cerist.dz/en/PresentationRevue/514"},
    {"name": "The Responsible Manager\'s Journal", "url": "https://asjp.cerist.dz/en/PresentationRevue/950"},
    {"name": "Timsal n Tamazight", "url": "https://asjp.cerist.dz/en/PresentationRevue/244"},
    {"name": "Tox Algérie", "url": "https://asjp.cerist.dz/en/PresentationRevue/404"},
    {"name": "Traduction et Langues", "url": "https://asjp.cerist.dz/en/PresentationRevue/155"},
    {"name": "Turath", "url": "https://asjp.cerist.dz/en/PresentationRevue/920"},
    {"name": "UMAB PoLSMER", "url": "https://asjp.cerist.dz/en/PresentationRevue/871"},
    {"name": "Ussnan", "url": "https://asjp.cerist.dz/en/PresentationRevue/983"},
    {"name": "Verres Céramiques Composites", "url": "https://asjp.cerist.dz/en/PresentationRevue/66"},
    {"name": "algerian journal of environmental science and technology", "url": "https://asjp.cerist.dz/en/PresentationRevue/285"},
    {"name": "annales de la faculte de droit", "url": "https://asjp.cerist.dz/en/PresentationRevue/556"},
    {"name": "cahiers de langue et de litterature", "url": "https://asjp.cerist.dz/en/PresentationRevue/186"},
    {"name": "e-Algerian Journal of Health & Research", "url": "https://asjp.cerist.dz/en/PresentationRevue/968"},
    {"name": "journal algérien de médecine", "url": "https://asjp.cerist.dz/en/PresentationRevue/506"},
    {"name": "khazzartech الاقتصاد الصناعي", "url": "https://asjp.cerist.dz/en/PresentationRevue/83"},
    {"name": "les cahiers du LADREN", "url": "https://asjp.cerist.dz/en/PresentationRevue/173"},
    {"name": "les cahiers du mecas", "url": "https://asjp.cerist.dz/en/PresentationRevue/174"},
    {"name": "recherches économiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/277"},
    {"name": "revue algerienne des études sociologiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/481"},
    {"name": "revue critique de droit et sciences politiques", "url": "https://asjp.cerist.dz/en/PresentationRevue/381"},
    {"name": "revue de bibliothéconomie", "url": "https://asjp.cerist.dz/en/PresentationRevue/239"},
    {"name": "social and human sciences review مجلة العلوم الاجتماعية والانسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/97"},
    {"name": "آفاق سينمائية", "url": "https://asjp.cerist.dz/en/PresentationRevue/158"},
    {"name": "آفاق علمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/232"},
    {"name": "أبحاث", "url": "https://asjp.cerist.dz/en/PresentationRevue/171"},
    {"name": "أبحاث إقتصادية معاصرة", "url": "https://asjp.cerist.dz/en/PresentationRevue/623"},
    {"name": "أبحاث قانونية وسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/471"},
    {"name": "أبعاد إقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/279"},
    {"name": "أبعــاد", "url": "https://asjp.cerist.dz/en/PresentationRevue/403"},
    {"name": "أبوليوس", "url": "https://asjp.cerist.dz/en/PresentationRevue/460"},
    {"name": "أدبيات", "url": "https://asjp.cerist.dz/en/PresentationRevue/745"},
    {"name": "أسئلة و رؤى", "url": "https://asjp.cerist.dz/en/PresentationRevue/833"},
    {"name": "أطراس", "url": "https://asjp.cerist.dz/en/PresentationRevue/880"},
    {"name": "أفاق معرفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/980"},
    {"name": "أفانين الخطاب", "url": "https://asjp.cerist.dz/en/PresentationRevue/801"},
    {"name": "أفكار وآفاق", "url": "https://asjp.cerist.dz/en/PresentationRevue/221"},
    {"name": "أقلام", "url": "https://asjp.cerist.dz/en/PresentationRevue/860"},
    {"name": "أمارات في اللغة والادب والنقد", "url": "https://asjp.cerist.dz/en/PresentationRevue/701"},
    {"name": "أنثروبولوجيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/79"},
    {"name": "أوراق", "url": "https://asjp.cerist.dz/en/PresentationRevue/791"},
    {"name": "أيقونات", "url": "https://asjp.cerist.dz/en/PresentationRevue/135"},
    {"name": "إدارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/667"},
    {"name": "إشارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/549"},
    {"name": "افاق فكرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/396"},
    {"name": "افاق للعلوم", "url": "https://asjp.cerist.dz/en/PresentationRevue/351"},
    {"name": "الآداب", "url": "https://asjp.cerist.dz/en/PresentationRevue/62"},
    {"name": "الآداب و اللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/371"},
    {"name": "الأسرة والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/236"},
    {"name": "الأفاق للدراسات الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/311"},
    {"name": "الإبتكار والتنمية الصناعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/775"},
    {"name": "الإبراهيمي للآداب والعلوم الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/634"},
    {"name": "الإحياء", "url": "https://asjp.cerist.dz/en/PresentationRevue/92"},
    {"name": "الإشعاع", "url": "https://asjp.cerist.dz/en/PresentationRevue/140"},
    {"name": "الاقتصاد والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/299"},
    {"name": "الاكاديمية للدراسات الاجتماعية و الانسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/552"},
    {"name": "الباحث", "url": "https://asjp.cerist.dz/en/PresentationRevue/307"},
    {"name": "الباحث", "url": "https://asjp.cerist.dz/en/PresentationRevue/359"},
    {"name": "الباحث في العلوم القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/848"},
    {"name": "التحبير", "url": "https://asjp.cerist.dz/en/PresentationRevue/747"},
    {"name": "التحدي", "url": "https://asjp.cerist.dz/en/PresentationRevue/71"},
    {"name": "التدوين", "url": "https://asjp.cerist.dz/en/PresentationRevue/377"},
    {"name": "التراث", "url": "https://asjp.cerist.dz/en/PresentationRevue/323"},
    {"name": "التربية والابستمولوجيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/344"},
    {"name": "التعليمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/184"},
    {"name": "التكامل الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/180"},
    {"name": "التواصلية", "url": "https://asjp.cerist.dz/en/PresentationRevue/294"},
    {"name": "التّواصل الأدبي", "url": "https://asjp.cerist.dz/en/PresentationRevue/82"},
    {"name": "الجميل", "url": "https://asjp.cerist.dz/en/PresentationRevue/1016"},
    {"name": "الحوار الثقافي", "url": "https://asjp.cerist.dz/en/PresentationRevue/206"},
    {"name": "الحوار الفكري", "url": "https://asjp.cerist.dz/en/PresentationRevue/179"},
    {"name": "الحوار المتوسطي", "url": "https://asjp.cerist.dz/en/PresentationRevue/281"},
    {"name": "الحوكمة والقانون الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/785"},
    {"name": "الخطاب", "url": "https://asjp.cerist.dz/en/PresentationRevue/346"},
    {"name": "الخطاب والتواصل", "url": "https://asjp.cerist.dz/en/PresentationRevue/205"},
    {"name": "الدراسات الإستراتيجية والبحوث السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/845"},
    {"name": "الدراسات الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/726"},
    {"name": "الدراسات القانونية المقارنة", "url": "https://asjp.cerist.dz/en/PresentationRevue/141"},
    {"name": "الذاكرة", "url": "https://asjp.cerist.dz/en/PresentationRevue/476"},
    {"name": "الراشدية", "url": "https://asjp.cerist.dz/en/PresentationRevue/399"},
    {"name": "الرواق", "url": "https://asjp.cerist.dz/en/PresentationRevue/289"},
    {"name": "الريادة لاقتصاديات الأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/510"},
    {"name": "الزهير للدراسات والبحوث الاتصالية والإعلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/813"},
    {"name": "الساورة للدراسات الانسانية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/536"},
    {"name": "السياسة العالمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/455"},
    {"name": "الصراط", "url": "https://asjp.cerist.dz/en/PresentationRevue/412"},
    {"name": "الصوتيات", "url": "https://asjp.cerist.dz/en/PresentationRevue/287"},
    {"name": "الصورة والاتصال", "url": "https://asjp.cerist.dz/en/PresentationRevue/169"},
    {"name": "العربية", "url": "https://asjp.cerist.dz/en/PresentationRevue/376"},
    {"name": "العلامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/488"},
    {"name": "العمدة في اللسانيات وتحليل الخطاب", "url": "https://asjp.cerist.dz/en/PresentationRevue/485"},
    {"name": "العمران البشري", "url": "https://asjp.cerist.dz/en/PresentationRevue/1006"},
    {"name": "الفضاء المغاربي", "url": "https://asjp.cerist.dz/en/PresentationRevue/393"},
    {"name": "الفكر المتوسطي", "url": "https://asjp.cerist.dz/en/PresentationRevue/185"},
    {"name": "القارئ للدراسات الأدبية و النقدية و اللغوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/498"},
    {"name": "القانون", "url": "https://asjp.cerist.dz/en/PresentationRevue/325"},
    {"name": "القانون العقاري و البيئة", "url": "https://asjp.cerist.dz/en/PresentationRevue/537"},
    {"name": "الكَلِم", "url": "https://asjp.cerist.dz/en/PresentationRevue/513"},
    {"name": "اللسانيات التطبيقية", "url": "https://asjp.cerist.dz/en/PresentationRevue/658"},
    {"name": "اللسانيات والترجمة", "url": "https://asjp.cerist.dz/en/PresentationRevue/830"},
    {"name": "اللغة والأدب", "url": "https://asjp.cerist.dz/en/PresentationRevue/330"},
    {"name": "اللّغة العربية", "url": "https://asjp.cerist.dz/en/PresentationRevue/219"},
    {"name": "المجلة الأكادمية للبحوث القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/441"},
    {"name": "المجلة الأورومتوسطية لاقتصاديات السياحة و الفندقة", "url": "https://asjp.cerist.dz/en/PresentationRevue/630"},
    {"name": "المجلة الافريقية للدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/540"},
    {"name": "المجلة التاريخية الجزائرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/664"},
    {"name": "المجلة الجزائرية التربية والصحة النفسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/356"},
    {"name": "المجلة الجزائرية لبحوث الإعلام والرأي العام", "url": "https://asjp.cerist.dz/en/PresentationRevue/641"},
    {"name": "المجلة الجزائرية لقانون الاعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/753"},
    {"name": "المجلة الجزائرية للأبحاث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/490"},
    {"name": "المجلة الجزائرية للأمن الإنساني", "url": "https://asjp.cerist.dz/en/PresentationRevue/474"},
    {"name": "المجلة الجزائرية للأمن والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/291"},
    {"name": "المجلة الجزائرية للإقتصاد الإسلامي", "url": "https://asjp.cerist.dz/en/PresentationRevue/955"},
    {"name": "المجلة الجزائرية للابحاث الاقتصادية والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/638"},
    {"name": "المجلة الجزائرية للاقتصاد السياسي", "url": "https://asjp.cerist.dz/en/PresentationRevue/670"},
    {"name": "المجلة الجزائرية للاقتصاد والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/306"},
    {"name": "المجلة الجزائرية للبحوث النفسية والتربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/997"},
    {"name": "المجلة الجزائرية للبحوث والدراسات التاريخية المتوسطية", "url": "https://asjp.cerist.dz/en/PresentationRevue/265"},
    {"name": "المجلة الجزائرية للتنمية الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/100"},
    {"name": "المجلة الجزائرية للحقوق والعلوم السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/526"},
    {"name": "المجلة الجزائرية للدراسات الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/948"},
    {"name": "المجلة الجزائرية للدراسات الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/629"},
    {"name": "المجلة الجزائرية للدراسات الاقتصادية والإدارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/903"},
    {"name": "المجلة الجزائرية للدراسات التاريخية والقانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/215"},
    {"name": "المجلة الجزائرية للدراسات السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/209"},
    {"name": "المجلة الجزائرية للدراسات المالية والمصرفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/497"},
    {"name": "المجلة الجزائرية للدراسات المحاسبية والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/114"},
    {"name": "المجلة الجزائرية للسياسة العامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/262"},
    {"name": "المجلة الجزائرية للسياسة والأمن", "url": "https://asjp.cerist.dz/en/PresentationRevue/832"},
    {"name": "المجلة الجزائرية للطفولة والتربية", "url": "https://asjp.cerist.dz/en/PresentationRevue/350"},
    {"name": "المجلة الجزائرية للعلوم", "url": "https://asjp.cerist.dz/en/PresentationRevue/982"},
    {"name": "المجلة الجزائرية للعلوم الإجتماعية والإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/259"},
    {"name": "المجلة الجزائرية للعلوم السياسية والعلاقات الدولية", "url": "https://asjp.cerist.dz/en/PresentationRevue/585"},
    {"name": "المجلة الجزائرية للعلوم القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/682"},
    {"name": "المجلة الجزائرية للعولمة و السياسات الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/249"},
    {"name": "المجلة الجزائرية للقانون البحري و النقل", "url": "https://asjp.cerist.dz/en/PresentationRevue/553"},
    {"name": "المجلة الجزائرية للقانون والعدالة", "url": "https://asjp.cerist.dz/en/PresentationRevue/447"},
    {"name": "المجلة الجزائرية للمالية الاسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/970"},
    {"name": "المجلة الجزائرية للمخطوطات", "url": "https://asjp.cerist.dz/en/PresentationRevue/160"},
    {"name": "المجلة الدولية للاتصال الاجتماعي", "url": "https://asjp.cerist.dz/en/PresentationRevue/524"},
    {"name": "المجلة الدولية للاداء الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/640"},
    {"name": "المجلة الدولية للبحوث القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/473"},
    {"name": "المجلة الدولية للدراسات الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/881"},
    {"name": "المجلة الدولية للدراسات الاقتصادية الاسلامية المتقدمة", "url": "https://asjp.cerist.dz/en/PresentationRevue/976"},
    {"name": "المجلة الدولية للدراسات التسويقية", "url": "https://asjp.cerist.dz/en/PresentationRevue/895"},
    {"name": "المجلة الدولية للدراسات و الابحاث في علوم الرياضة و التدريب", "url": "https://asjp.cerist.dz/en/PresentationRevue/774"},
    {"name": "المجلة الشاملة للحقوق", "url": "https://asjp.cerist.dz/en/PresentationRevue/711"},
    {"name": "المجلة العلمية للتربية البدنية و الرياضية", "url": "https://asjp.cerist.dz/en/PresentationRevue/452"},
    {"name": "المجلة العلمية للحوار الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/912"},
    {"name": "المجلة المتوسطية للقانون والإقتصاد", "url": "https://asjp.cerist.dz/en/PresentationRevue/570"},
    {"name": "المجلة المغاربية للإقتصاد و المانجمت", "url": "https://asjp.cerist.dz/en/PresentationRevue/138"},
    {"name": "المجلة المغاربية للدراسات التاريخية والإجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/334"},
    {"name": "المجلة المغاربية للمخطوطات", "url": "https://asjp.cerist.dz/en/PresentationRevue/229"},
    {"name": "المجلّة الجزائرية للقانون المقارن", "url": "https://asjp.cerist.dz/en/PresentationRevue/355"},
    {"name": "المحترف", "url": "https://asjp.cerist.dz/en/PresentationRevue/380"},
    {"name": "المحلل القانوني", "url": "https://asjp.cerist.dz/en/PresentationRevue/846"},
    {"name": "المداد", "url": "https://asjp.cerist.dz/en/PresentationRevue/327"},
    {"name": "المدونة", "url": "https://asjp.cerist.dz/en/PresentationRevue/253"},
    {"name": "المربي", "url": "https://asjp.cerist.dz/en/PresentationRevue/580"},
    {"name": "المرتقى", "url": "https://asjp.cerist.dz/en/PresentationRevue/607"},
    {"name": "المشكاة في الاقتصاد التنمية و القانون", "url": "https://asjp.cerist.dz/en/PresentationRevue/162"},
    {"name": "المصادر", "url": "https://asjp.cerist.dz/en/PresentationRevue/29"},
    {"name": "المصطلح", "url": "https://asjp.cerist.dz/en/PresentationRevue/924"},
    {"name": "المعيار", "url": "https://asjp.cerist.dz/en/PresentationRevue/317"},
    {"name": "المعيار", "url": "https://asjp.cerist.dz/en/PresentationRevue/90"},
    {"name": "المـجــــلــــة العـــلمـــيـــة المـسـتـقـبــــل الاقــتــصــــــادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/583"},
    {"name": "المفكر", "url": "https://asjp.cerist.dz/en/PresentationRevue/456"},
    {"name": "المقاصد في اللغة والأدب", "url": "https://asjp.cerist.dz/en/PresentationRevue/878"},
    {"name": "المقريزي للدراسـات الاقتصادية والمـالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/650"},
    {"name": "الممارسات اللّغويّة", "url": "https://asjp.cerist.dz/en/PresentationRevue/352"},
    {"name": "المنار للدراسات والبحوث القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/419"},
    {"name": "المناهل", "url": "https://asjp.cerist.dz/en/PresentationRevue/669"},
    {"name": "المنتقى للبحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/771"},
    {"name": "الموروث", "url": "https://asjp.cerist.dz/en/PresentationRevue/333"},
    {"name": "المُزْهِر", "url": "https://asjp.cerist.dz/en/PresentationRevue/877"},
    {"name": "الناص", "url": "https://asjp.cerist.dz/en/PresentationRevue/966"},
    {"name": "الناصرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/144"},
    {"name": "النص", "url": "https://asjp.cerist.dz/en/PresentationRevue/500"},
    {"name": "الوقاية والأرغنوميا", "url": "https://asjp.cerist.dz/en/PresentationRevue/448"},
    {"name": "بحوث سيميائية", "url": "https://asjp.cerist.dz/en/PresentationRevue/382"},
    {"name": "بدايات", "url": "https://asjp.cerist.dz/en/PresentationRevue/653"},
    {"name": "بصمة للأبحاث العلمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/991"},
    {"name": "تاريخ العلوم", "url": "https://asjp.cerist.dz/en/PresentationRevue/348"},
    {"name": "تافزا", "url": "https://asjp.cerist.dz/en/PresentationRevue/812"},
    {"name": "تجسير للأبحاث والدراسات متعددة التخصصات", "url": "https://asjp.cerist.dz/en/PresentationRevue/824"},
    {"name": "تداوليات", "url": "https://asjp.cerist.dz/en/PresentationRevue/1003"},
    {"name": "تدفقات فلسفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/876"},
    {"name": "تطوير", "url": "https://asjp.cerist.dz/en/PresentationRevue/143"},
    {"name": "تمثلات", "url": "https://asjp.cerist.dz/en/PresentationRevue/586"},
    {"name": "تنمية الموارد البشرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/183"},
    {"name": "جديد الاقتصاد", "url": "https://asjp.cerist.dz/en/PresentationRevue/342"},
    {"name": "جذور المعرفة", "url": "https://asjp.cerist.dz/en/PresentationRevue/926"},
    {"name": "جسور المعرفة", "url": "https://asjp.cerist.dz/en/PresentationRevue/136"},
    {"name": "جماليات", "url": "https://asjp.cerist.dz/en/PresentationRevue/525"},
    {"name": "حوسبة اللغة العربية", "url": "https://asjp.cerist.dz/en/PresentationRevue/759"},
    {"name": "حوليات الآداب واللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/312"},
    {"name": "حوليات التاريخ والجغرافيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/242"},
    {"name": "حوليات جامعة الجزائر 2", "url": "https://asjp.cerist.dz/en/PresentationRevue/939"},
    {"name": "حوليات جامعة بشار", "url": "https://asjp.cerist.dz/en/PresentationRevue/194"},
    {"name": "حوليات جامعة بشار في العلوم الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/659"},
    {"name": "حوليات جامعة قالمة للعلوم الاجتماعية والإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/96"},
    {"name": "دراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/332"},
    {"name": "دراسات أدبية", "url": "https://asjp.cerist.dz/en/PresentationRevue/252"},
    {"name": "دراسات إسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/591"},
    {"name": "دراسات إقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/590"},
    {"name": "دراسات إنسانية واجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/21"},
    {"name": "دراسات اجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/257"},
    {"name": "دراسات استراتيجية", "url": "https://asjp.cerist.dz/en/PresentationRevue/250"},
    {"name": "دراسات اقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/67"},
    {"name": "دراسات اقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/417"},
    {"name": "دراسات تاريخية", "url": "https://asjp.cerist.dz/en/PresentationRevue/256"},
    {"name": "دراسات تراثية", "url": "https://asjp.cerist.dz/en/PresentationRevue/423"},
    {"name": "دراسات فلسفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/230"},
    {"name": "دراسات فنية", "url": "https://asjp.cerist.dz/en/PresentationRevue/702"},
    {"name": "دراسات في التنمية والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/148"},
    {"name": "دراسات في العلوم الإنسانية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/364"},
    {"name": "دراسات في علم الارطوفوبيا وعلم النفس العصبي", "url": "https://asjp.cerist.dz/en/PresentationRevue/581"},
    {"name": "دراسات في علوم الانسان والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/765"},
    {"name": "دراسات في علوم التربية", "url": "https://asjp.cerist.dz/en/PresentationRevue/216"},
    {"name": "دراسات قانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/266"},
    {"name": "دراسات قانونية وسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/449"},
    {"name": "دراسات لسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/319"},
    {"name": "دراسات معاصرة", "url": "https://asjp.cerist.dz/en/PresentationRevue/297"},
    {"name": "دراسات نفسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/288"},
    {"name": "دراسات نفسية وتربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/763"},
    {"name": "دراسات نفسية وتربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/117"},
    {"name": "دراسات نقدية", "url": "https://asjp.cerist.dz/en/PresentationRevue/885"},
    {"name": "دراسات وأبحاث", "url": "https://asjp.cerist.dz/en/PresentationRevue/20"},
    {"name": "دفاتر البحوث العلمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/595"},
    {"name": "دفاتر السياسة والقانون", "url": "https://asjp.cerist.dz/en/PresentationRevue/120"},
    {"name": "دفاتر المتوسط", "url": "https://asjp.cerist.dz/en/PresentationRevue/487"},
    {"name": "دفاتر المخبر", "url": "https://asjp.cerist.dz/en/PresentationRevue/483"},
    {"name": "دفاتر في اللسانيات والتعليمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/177"},
    {"name": "دفاتر مخبر الشعرية الجزائرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/459"},
    {"name": "دليل الآداب و اللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/851"},
    {"name": "ذخائر اللغة", "url": "https://asjp.cerist.dz/en/PresentationRevue/841"},
    {"name": "رؤى تاريخية لألبحاث و الدراسات المتوسطية", "url": "https://asjp.cerist.dz/en/PresentationRevue/718"},
    {"name": "رؤى في الآداب والعلوم الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/725"},
    {"name": "رسالة المسجد", "url": "https://asjp.cerist.dz/en/PresentationRevue/728"},
    {"name": "رفوف", "url": "https://asjp.cerist.dz/en/PresentationRevue/132"},
    {"name": "رُؤىَ فِكرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/838"},
    {"name": "سلسلة الأنوار", "url": "https://asjp.cerist.dz/en/PresentationRevue/782"},
    {"name": "سلوك", "url": "https://asjp.cerist.dz/en/PresentationRevue/188"},
    {"name": "سوسيولوجيا الجريمة للبحوث والدراسات العلمية في الظواهر الاجرامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/925"},
    {"name": "سوسيولوجيون", "url": "https://asjp.cerist.dz/en/PresentationRevue/721"},
    {"name": "عصور", "url": "https://asjp.cerist.dz/en/PresentationRevue/167"},
    {"name": "فتوحات", "url": "https://asjp.cerist.dz/en/PresentationRevue/68"},
    {"name": "فصل الخطاب", "url": "https://asjp.cerist.dz/en/PresentationRevue/81"},
    {"name": "في الترجمة", "url": "https://asjp.cerist.dz/en/PresentationRevue/95"},
    {"name": "قراءات", "url": "https://asjp.cerist.dz/en/PresentationRevue/113"},
    {"name": "قراءات", "url": "https://asjp.cerist.dz/en/PresentationRevue/405"},
    {"name": "قرطاس الدراسات الحضارية و الفكرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/558"},
    {"name": "قضايا الأدب", "url": "https://asjp.cerist.dz/en/PresentationRevue/439"},
    {"name": "قضايا تاريخية", "url": "https://asjp.cerist.dz/en/PresentationRevue/228"},
    {"name": "قضايا لغوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/872"},
    {"name": "لغة كلام", "url": "https://asjp.cerist.dz/en/PresentationRevue/176"},
    {"name": "متون", "url": "https://asjp.cerist.dz/en/PresentationRevue/146"},
    {"name": "مجاميع المعرفة", "url": "https://asjp.cerist.dz/en/PresentationRevue/347"},
    {"name": "مجـــــــــــــــــــــــلة التحــــولات الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/808"},
    {"name": "مجـــــــــــــــــــــــلة المشكلة الاقـــــــــــــــــــتصادية والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/823"},
    {"name": "مجلة آفاق لعلم الاجتماع", "url": "https://asjp.cerist.dz/en/PresentationRevue/278"},
    {"name": "مجلة آفاق للأبحاث السياسية والقانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/744"},
    {"name": "مجلة آفاق للبحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/665"},
    {"name": "مجلة أبحاث", "url": "https://asjp.cerist.dz/en/PresentationRevue/435"},
    {"name": "مجلة أبحاث كمية ونوعية في العلوم الاقتصادية والادارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/756"},
    {"name": "مجلة أبحاث ودراسات التنمية - Revue Recherches et Etudes en Développement -", "url": "https://asjp.cerist.dz/en/PresentationRevue/57"},
    {"name": "مجلة أداء المؤسسات الجزائرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/103"},
    {"name": "مجلة أدب الطفل", "url": "https://asjp.cerist.dz/en/PresentationRevue/933"},
    {"name": "مجلة أراء للدراسات الاقتصادية والادارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/647"},
    {"name": "مجلة أرصاد للدراسات الاقتصادية والإدارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/628"},
    {"name": "مجلة أسلوبيّات", "url": "https://asjp.cerist.dz/en/PresentationRevue/862"},
    {"name": "مجلة أصيل للدراسات النفسية و التربوية و الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/947"},
    {"name": "مجلة أنثروبولوجية الأديان", "url": "https://asjp.cerist.dz/en/PresentationRevue/559"},
    {"name": "مجلة أنسنة للبحوث و الدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/320"},
    {"name": "مجلة أوراق إقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/472"},
    {"name": "مجلة أوراق بحثية", "url": "https://asjp.cerist.dz/en/PresentationRevue/799"},
    {"name": "مجلة إحالات", "url": "https://asjp.cerist.dz/en/PresentationRevue/587"},
    {"name": "مجلة إدارة الأعمال والدراسات الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/313"},
    {"name": "مجلة إسهامات للبحوث و الدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/746"},
    {"name": "مجلة إشكالات في اللغة و الأدب", "url": "https://asjp.cerist.dz/en/PresentationRevue/238"},
    {"name": "مجلة إضاءات علمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/827"},
    {"name": "مجلة إضاءات للعلوم الانسانية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/741"},
    {"name": "مجلة إضافات إقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/443"},
    {"name": "مجلة إقتصاد المال والأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/468"},
    {"name": "مجلة إنسانيات معاصرة للبحوث والدراسات في العلوم الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/882"},
    {"name": "مجلة إيليزا للبحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/433"},
    {"name": "مجلة ابحاث", "url": "https://asjp.cerist.dz/en/PresentationRevue/508"},
    {"name": "مجلة ابن خلدون للإبداع والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/709"},
    {"name": "مجلة ارتقاء للبحوث و الدراسات الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/699"},
    {"name": "مجلة استراتيجيات ضمان الجودة", "url": "https://asjp.cerist.dz/en/PresentationRevue/740"},
    {"name": "مجلة اسهامات قانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/897"},
    {"name": "مجلة اقتصاد المال و الأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/109"},
    {"name": "مجلة اقتصاد المنظمات والتنمية المستدامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/967"},
    {"name": "مجلة اقتصاديات الاعمال والتجارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/480"},
    {"name": "مجلة اقتصاديات النقود والتمويل", "url": "https://asjp.cerist.dz/en/PresentationRevue/904"},
    {"name": "مجلة اقتصاديات شمال افريقيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/9"},
    {"name": "مجلة الآداب و العلوم الإجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/4"},
    {"name": "مجلة الآداب و العلوم الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/98"},
    {"name": "مجلة الآداب والعلوم الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/56"},
    {"name": "مجلة الآداب والعلوم الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/354"},
    {"name": "مجلة الآداب والعلوم الانسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/575"},
    {"name": "مجلة الآداب واللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/308"},
    {"name": "مجلة الآداب واللغات والعلوم الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/652"},
    {"name": "مجلة الأبحاث القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/621"},
    {"name": "مجلة الأثر للدراسات النفسية والتربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/616"},
    {"name": "مجلة الأحمدي للدراسات اللغوية والنقدية والترجمة", "url": "https://asjp.cerist.dz/en/PresentationRevue/858"},
    {"name": "مجلة الأداء", "url": "https://asjp.cerist.dz/en/PresentationRevue/894"},
    {"name": "مجلة الأصالة للدراسات والبحوث", "url": "https://asjp.cerist.dz/en/PresentationRevue/807"},
    {"name": "مجلة الأصيل للبحوث الاقتصادية والإدارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/462"},
    {"name": "مجلة الأعمال الإلكترونية والاقتصاد الرقمي", "url": "https://asjp.cerist.dz/en/PresentationRevue/930"},
    {"name": "مجلة الأكاديمة للبحوث في العلوم الإجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/648"},
    {"name": "مجلة الأكاديمية الدولية للعلوم النفسية والتربوية والأرطفونيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/773"},
    {"name": "مجلة الإبتكار والتسويق", "url": "https://asjp.cerist.dz/en/PresentationRevue/204"},
    {"name": "مجلة الإبداع", "url": "https://asjp.cerist.dz/en/PresentationRevue/269"},
    {"name": "مجلة الإبراهيمي للدراسات لنفسية والتربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/737"},
    {"name": "مجلة الإدارة العامة و القانون و التنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/786"},
    {"name": "مجلة الإدارة والتنمية للبحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/273"},
    {"name": "مجلة الإدارة وريادة الأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/972"},
    {"name": "مجلة الإستراتيجية والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/276"},
    {"name": "مجلة الإعلام والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/496"},
    {"name": "مجلة الإقتصاد الجديد", "url": "https://asjp.cerist.dz/en/PresentationRevue/296"},
    {"name": "مجلة الإقتصاد و المجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/17"},
    {"name": "مجلة الإناسة و علوم المجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/783"},
    {"name": "مجلة الإنسان والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/192"},
    {"name": "مجلة الابداع الرياضي", "url": "https://asjp.cerist.dz/en/PresentationRevue/316"},
    {"name": "مجلة الابراهيمي للعلوم الاجتماعية والانسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/684"},
    {"name": "مجلة الاجتهاد القضائي", "url": "https://asjp.cerist.dz/en/PresentationRevue/124"},
    {"name": "مجلة الاجتهاد للدراسات القانونية والاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/222"},
    {"name": "مجلة الاداب واللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/271"},
    {"name": "مجلة الاستاذ الباحث للدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/457"},
    {"name": "مجلة الاستثمار والتنمية المستدامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/879"},
    {"name": "مجلة الاستراتيجية والانفتاح الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/1015"},
    {"name": "مجلة الاستيعاب", "url": "https://asjp.cerist.dz/en/PresentationRevue/761"},
    {"name": "مجلة الاقتصاد الحديث والتنمية المستدامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/602"},
    {"name": "مجلة الاقتصاد الدولي والعولمة", "url": "https://asjp.cerist.dz/en/PresentationRevue/622"},
    {"name": "مجلة الاقتصاد و التنمية البشرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/275"},
    {"name": "مجلة الاقتصاد وادارة الاعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/515"},
    {"name": "مجلة الاقتصاد والبيئة", "url": "https://asjp.cerist.dz/en/PresentationRevue/645"},
    {"name": "مجلة الاقتصاد والتجارة الدولية", "url": "https://asjp.cerist.dz/en/PresentationRevue/835"},
    {"name": "مجلة الاقتصاد والتنمية المستدامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/598"},
    {"name": "مجلة الاقتصاد والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/150"},
    {"name": "مجلة الامتياز لبحــوث الاقتصاد والادارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/440"},
    {"name": "مجلة الانسان والمجال", "url": "https://asjp.cerist.dz/en/PresentationRevue/326"},
    {"name": "مجلة الباحث", "url": "https://asjp.cerist.dz/en/PresentationRevue/7"},
    {"name": "مجلة الباحث", "url": "https://asjp.cerist.dz/en/PresentationRevue/345"},
    {"name": "مجلة الباحث الإقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/85"},
    {"name": "مجلة الباحث الاجتماعي", "url": "https://asjp.cerist.dz/en/PresentationRevue/73"},
    {"name": "مجلة الباحث الاقتصادي - Economics Researcher\'s Journal -", "url": "https://asjp.cerist.dz/en/PresentationRevue/61"},
    {"name": "مجلة الباحث الاكاديمي في العلوم القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/668"},
    {"name": "مجلة الباحث القانوني", "url": "https://asjp.cerist.dz/en/PresentationRevue/723"},
    {"name": "مجلة الباحث في الأرطوفونيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/989"},
    {"name": "مجلة الباحث في العلوم الإنسانية و الإجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/119"},
    {"name": "مجلة الباحث في العلوم الانسانية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/503"},
    {"name": "مجلة الباحث للدراسات الأكاديمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/86"},
    {"name": "مجلة الباحث للعلوم الرياضية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/698"},
    {"name": "مجلة البحث القانوني والسياسي", "url": "https://asjp.cerist.dz/en/PresentationRevue/458"},
    {"name": "مجلة البحوث الأسرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/769"},
    {"name": "مجلة البحوث الادارية والاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/604"},
    {"name": "مجلة البحوث الاقتصادية المتقدمة", "url": "https://asjp.cerist.dz/en/PresentationRevue/494"},
    {"name": "مجلة البحوث الاقتصادية والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/64"},
    {"name": "مجلة البحوث التاريخية", "url": "https://asjp.cerist.dz/en/PresentationRevue/492"},
    {"name": "مجلة البحوث التربوية والتعليمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/241"},
    {"name": "مجلة البحوث السياسية و الادارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/314"},
    {"name": "مجلة البحوث العلمية في التشريعات البيئية", "url": "https://asjp.cerist.dz/en/PresentationRevue/151"},
    {"name": "مجلة البحوث العلمية والدراسات الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/264"},
    {"name": "مجلة البحوث القانونية و الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/512"},
    {"name": "مجلة البحوث القانونية و السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/560"},
    {"name": "مجلة البحوث في الحقوق والعلوم السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/187"},
    {"name": "مجلة البحوث في العقود و قانون الأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/610"},
    {"name": "مجلة البحوث في العلوم المالية والمحاسبية", "url": "https://asjp.cerist.dz/en/PresentationRevue/99"},
    {"name": "مجلة البحوث في علوم وتقنيات النشاط البدني والرياضي", "url": "https://asjp.cerist.dz/en/PresentationRevue/738"},
    {"name": "مجلة البحوث و الدراسات الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/77"},
    {"name": "مجلة البحوث و الدراسات التجارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/442"},
    {"name": "مجلة البحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/202"},
    {"name": "مجلة البحوث والدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/272"},
    {"name": "مجلة البحوث والدراسات المعاصرة", "url": "https://asjp.cerist.dz/en/PresentationRevue/952"},
    {"name": "مجلة البدر", "url": "https://asjp.cerist.dz/en/PresentationRevue/343"},
    {"name": "مجلة البديل الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/400"},
    {"name": "مجلة البشائر الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/196"},
    {"name": "مجلة البصائر للبحوث في العلوم الاقتصادية والتجارية وعلوم التسيير", "url": "https://asjp.cerist.dz/en/PresentationRevue/905"},
    {"name": "مجلة البصائر للدراسات القانونية والاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/822"},
    {"name": "مجلة البناء الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/696"},
    {"name": "مجلة البيئة والتنمية المستدامة وصحة الإنسان", "url": "https://asjp.cerist.dz/en/PresentationRevue/854"},
    {"name": "مجلة البيان للأبنية الفكرية و الحضارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/890"},
    {"name": "مجلة البيبان للدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/796"},
    {"name": "مجلة التأويل و تحليل الخطاب", "url": "https://asjp.cerist.dz/en/PresentationRevue/760"},
    {"name": "مجلة التاريخ المتوسطي", "url": "https://asjp.cerist.dz/en/PresentationRevue/605"},
    {"name": "مجلة التحليل الاقتصادي ودراسات التنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/902"},
    {"name": "مجلة التحليل و الاستشراف الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/768"},
    {"name": "مجلة التربية البدنية والرياضية", "url": "https://asjp.cerist.dz/en/PresentationRevue/936"},
    {"name": "مجلة التربية والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/932"},
    {"name": "مجلة التشريع الاعلامي", "url": "https://asjp.cerist.dz/en/PresentationRevue/868"},
    {"name": "مجلة التعمير والبناء", "url": "https://asjp.cerist.dz/en/PresentationRevue/534"},
    {"name": "مجلة التغير الاجتماعي", "url": "https://asjp.cerist.dz/en/PresentationRevue/486"},
    {"name": "مجلة التكامل", "url": "https://asjp.cerist.dz/en/PresentationRevue/873"},
    {"name": "مجلة التكامل في بحوث العلوم الاجتماعية والرياضية", "url": "https://asjp.cerist.dz/en/PresentationRevue/707"},
    {"name": "مجلة التمكين الاجتماعي", "url": "https://asjp.cerist.dz/en/PresentationRevue/644"},
    {"name": "مجلة التمويل والاستثمار والتنمية المستدامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/631"},
    {"name": "مجلة التميز", "url": "https://asjp.cerist.dz/en/PresentationRevue/673"},
    {"name": "مجلة التميز الفكري للعلوم الاجتماعية و الانسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/695"},
    {"name": "مجلة التنمية الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/336"},
    {"name": "مجلة التنمية البشرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/172"},
    {"name": "مجلة التنمية وإدارة الموارد البشرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/357"},
    {"name": "مجلة التنمية والاستشراف للبحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/424"},
    {"name": "مجلة التنمية والاقتصاد التطبيقي", "url": "https://asjp.cerist.dz/en/PresentationRevue/463"},
    {"name": "مجلة التنويع الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/809"},
    {"name": "مجلة الثقافة الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/719"},
    {"name": "مجلة الجامع في الدراسات النفسية والعلوم التربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/309"},
    {"name": "مجلة الحدث للدراسات المالية و الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/864"},
    {"name": "مجلة الحضارة الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/45"},
    {"name": "مجلة الحقوق والحريات", "url": "https://asjp.cerist.dz/en/PresentationRevue/123"},
    {"name": "مجلة الحقوق والعلوم الانسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/315"},
    {"name": "مجلة الحقوق والعلوم السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/298"},
    {"name": "مجلة الحقوق والعلوم السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/76"},
    {"name": "مجلة الحقيقة", "url": "https://asjp.cerist.dz/en/PresentationRevue/49"},
    {"name": "مجلة الحكمة للدراسات الأدبية واللغوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/199"},
    {"name": "مجلة الحكمة للدراسات الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/200"},
    {"name": "مجلة الحكمة للدراسات الاسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/770"},
    {"name": "مجلة الحكمة للدراسات الاعلامية والإتصالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/280"},
    {"name": "مجلة الحكمة للدراسات الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/198"},
    {"name": "مجلة الحكمة للدراسات التاريخية", "url": "https://asjp.cerist.dz/en/PresentationRevue/197"},
    {"name": "مجلة الحكمة للدراسات التربوية والنفسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/335"},
    {"name": "مجلة الحكمة للدراسات الفلسفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/338"},
    {"name": "مجلة الحوكمة، المسؤولية الإجتماعية والتنمية المستدامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/603"},
    {"name": "مجلة الخبير", "url": "https://asjp.cerist.dz/en/PresentationRevue/384"},
    {"name": "مجلة الخلدونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/563"},
    {"name": "مجلة الخليل في علوم اللسان", "url": "https://asjp.cerist.dz/en/PresentationRevue/797"},
    {"name": "مجلة الدراسات الأكاديمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/794"},
    {"name": "مجلة الدراسات الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/454"},
    {"name": "مجلة الدراسات الإفريقية", "url": "https://asjp.cerist.dz/en/PresentationRevue/233"},
    {"name": "مجلة الدراسات الإقتصادية الكمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/328"},
    {"name": "مجلة الدراسات الإقتصادية والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/127"},
    {"name": "مجلة الدراسات الاقتصادية المعاصرة", "url": "https://asjp.cerist.dz/en/PresentationRevue/469"},
    {"name": "مجلة الدراسات البيئية والتنمية المستدامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/978"},
    {"name": "مجلة الدراسات التاريخية", "url": "https://asjp.cerist.dz/en/PresentationRevue/38"},
    {"name": "مجلة الدراسات التاريخية العسكرية", "url": "https://asjp.cerist.dz/en/PresentationRevue/661"},
    {"name": "مجلة الدراسات التجارية والاقتصادية المعاصرة", "url": "https://asjp.cerist.dz/en/PresentationRevue/617"},
    {"name": "مجلة الدراسات التسويقية وإدارة الأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/544"},
    {"name": "مجلة الدراسات التنموية وريادة الأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/962"},
    {"name": "مجلة الدراسات الحقوقية", "url": "https://asjp.cerist.dz/en/PresentationRevue/137"},
    {"name": "مجلة الدراسات العقدية ومقارنة الأديان", "url": "https://asjp.cerist.dz/en/PresentationRevue/87"},
    {"name": "مجلة الدراسات الفقهية والقضائية", "url": "https://asjp.cerist.dz/en/PresentationRevue/106"},
    {"name": "مجلة الدراسات القانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/318"},
    {"name": "مجلة الدراسات القانونية والاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/649"},
    {"name": "مجلة الدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/304"},
    {"name": "مجلة الدراسات المالية والمحاسبية", "url": "https://asjp.cerist.dz/en/PresentationRevue/389"},
    {"name": "مجلة الدراسات المالية والمحاسبية والإدارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/58"},
    {"name": "مجلة الدراسات المحاسبية والمالية المتقدمة", "url": "https://asjp.cerist.dz/en/PresentationRevue/611"},
    {"name": "مجلة الدراسات حول فعلية القاعدة القانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/651"},
    {"name": "مجلة الدراسات والبحوث الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/475"},
    {"name": "مجلة الدراسات والبحوث القانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/461"},
    {"name": "مجلة الذخيرة للبحوث والدراسات الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/793"},
    {"name": "مجلة الذكاء الاقتصادي والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/929"},
    {"name": "مجلة الرائد في الدراسات السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/678"},
    {"name": "مجلة الراصد العلمي", "url": "https://asjp.cerist.dz/en/PresentationRevue/568"},
    {"name": "مجلة الراصد لدراسات العلوم الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/733"},
    {"name": "مجلة الرسالة للدراسات الإعلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/212"},
    {"name": "مجلة الرسالة للدراسات والبحوث الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/223"},
    {"name": "مجلة الرستمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/734"},
    {"name": "مجلة الروائز", "url": "https://asjp.cerist.dz/en/PresentationRevue/692"},
    {"name": "مجلة السراج في التربية وقضايا المجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/467"},
    {"name": "مجلة السلام للاقتصاد الإسلامي", "url": "https://asjp.cerist.dz/en/PresentationRevue/735"},
    {"name": "مجلة السلام للعلوم الإنسانية و الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/762"},
    {"name": "مجلة السوسيولسانيات وتحليل الخطاب", "url": "https://asjp.cerist.dz/en/PresentationRevue/855"},
    {"name": "مجلة السياق", "url": "https://asjp.cerist.dz/en/PresentationRevue/821"},
    {"name": "مجلة الشامل للعلوم التربوية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/491"},
    {"name": "مجلة الشريعة والاقتصاد", "url": "https://asjp.cerist.dz/en/PresentationRevue/91"},
    {"name": "مجلة الشريعة والدراسات الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/840"},
    {"name": "مجلة الشهاب", "url": "https://asjp.cerist.dz/en/PresentationRevue/391"},
    {"name": "مجلة الصدى الدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/817"},
    {"name": "مجلة الطفولة والعلوم وتنمية المجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/937"},
    {"name": "مجلة العبر للدراسات التاريخية و الاثرية في شمال افريقيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/564"},
    {"name": "مجلة العرفان للدراسات الصوفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/727"},
    {"name": "مجلة العلوم الإدارية والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/495"},
    {"name": "مجلة العلوم الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/784"},
    {"name": "مجلة العلوم الإسلامية والحضارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/295"},
    {"name": "مجلة العلوم الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/341"},
    {"name": "مجلة العلوم الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/511"},
    {"name": "مجلة العلوم الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/16"},
    {"name": "مجلة العلوم الإنسانية والإجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/639"},
    {"name": "مجلة العلوم الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/305"},
    {"name": "مجلة العلوم الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/189"},
    {"name": "مجلة العلوم الاجتماعية و الانسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/394"},
    {"name": "مجلة العلوم الاجتماعية والإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/65"},
    {"name": "مجلة العلوم الاقتصادية والتسيير والعلوم التجارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/324"},
    {"name": "مجلة العلوم الاقتصادية وعلوم التسيير", "url": "https://asjp.cerist.dz/en/PresentationRevue/63"},
    {"name": "مجلة العلوم الانسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/41"},
    {"name": "مجلة العلوم الانسانية لجامعة أم البواقي", "url": "https://asjp.cerist.dz/en/PresentationRevue/93"},
    {"name": "مجلة العلوم الانسانية والحضارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/730"},
    {"name": "مجلة العلوم القانونية و السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/110"},
    {"name": "مجلة العلوم القانونية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/434"},
    {"name": "مجلة العلوم النفسية والتربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/105"},
    {"name": "مجلة العلوم و التكنولوجية للنشاطات البدنية و الرياضية", "url": "https://asjp.cerist.dz/en/PresentationRevue/3"},
    {"name": "مجلة العلوم وافاق المعارف", "url": "https://asjp.cerist.dz/en/PresentationRevue/834"},
    {"name": "مجلة العَدْوِي للسانيات العرفنية وتعليمية اللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/804"},
    {"name": "مجلة الفتح للدراسات النفسية و التربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/657"},
    {"name": "مجلة الفقه القانوني والسياسي", "url": "https://asjp.cerist.dz/en/PresentationRevue/633"},
    {"name": "مجلة الفكر القانوني والسياسي", "url": "https://asjp.cerist.dz/en/PresentationRevue/445"},
    {"name": "مجلة القانون الدستوري والمؤسسات السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/541"},
    {"name": "مجلة القانون العام الجزائري والمقارن", "url": "https://asjp.cerist.dz/en/PresentationRevue/547"},
    {"name": "مجلة القانون العقاري", "url": "https://asjp.cerist.dz/en/PresentationRevue/688"},
    {"name": "مجلة القانون والأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/1004"},
    {"name": "مجلة القانون والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/600"},
    {"name": "مجلة القانون والتنمية المحلية", "url": "https://asjp.cerist.dz/en/PresentationRevue/608"},
    {"name": "مجلة القانون والعلوم البينية", "url": "https://asjp.cerist.dz/en/PresentationRevue/908"},
    {"name": "مجلة القانون والعلوم السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/518"},
    {"name": "مجلة القانون والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/133"},
    {"name": "مجلة القانون، المجتمع والسلطة", "url": "https://asjp.cerist.dz/en/PresentationRevue/153"},
    {"name": "مجلة القبس للدراسات النفسية والإجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/724"},
    {"name": "مجلة القرطاس للعلوم الإقتصادية والتجارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/914"},
    {"name": "مجلة القسطاس للعلوم الادارية و الاقتصادية و المالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/826"},
    {"name": "مجلة القيمة المضافة لاقتصاديات الاعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/642"},
    {"name": "مجلة اللغة العربية وآدابها", "url": "https://asjp.cerist.dz/en/PresentationRevue/286"},
    {"name": "مجلة اللغة والاتصال", "url": "https://asjp.cerist.dz/en/PresentationRevue/166"},
    {"name": "مجلة المؤشر", "url": "https://asjp.cerist.dz/en/PresentationRevue/811"},
    {"name": "مجلة المؤشر للدراسات الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/527"},
    {"name": "مجلة المجتمع والرياضة", "url": "https://asjp.cerist.dz/en/PresentationRevue/493"},
    {"name": "مجلة المجمع الجزائري للغة العربية", "url": "https://asjp.cerist.dz/en/PresentationRevue/410"},
    {"name": "مجلة المحاسبة التدقيق والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/643"},
    {"name": "مجلة المحامي", "url": "https://asjp.cerist.dz/en/PresentationRevue/974"},
    {"name": "مجلة المحكمة الدستورية", "url": "https://asjp.cerist.dz/en/PresentationRevue/267"},
    {"name": "مجلة المخبر\' أبحاث في اللغة والأدب الجزائري", "url": "https://asjp.cerist.dz/en/PresentationRevue/104"},
    {"name": "مجلة المرآة للدراسات المغاربية", "url": "https://asjp.cerist.dz/en/PresentationRevue/528"},
    {"name": "مجلة المسار الرياضي", "url": "https://asjp.cerist.dz/en/PresentationRevue/674"},
    {"name": "مجلة المسبار للدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/907"},
    {"name": "مجلة المستقبل للدراسات الاقتصادية المعمقة", "url": "https://asjp.cerist.dz/en/PresentationRevue/666"},
    {"name": "مجلة المصباح في علم النفس وعلوم التربية والأرطوفونيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/836"},
    {"name": "مجلة المعارف للبحوث والدراسات التاريخية", "url": "https://asjp.cerist.dz/en/PresentationRevue/111"},
    {"name": "مجلة المفكر", "url": "https://asjp.cerist.dz/en/PresentationRevue/131"},
    {"name": "مجلة المفكر للدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/632"},
    {"name": "مجلة المقار للدراسات الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/509"},
    {"name": "مجلة المقال", "url": "https://asjp.cerist.dz/en/PresentationRevue/69"},
    {"name": "مجلة المقاولاتية والتنمية المستدامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/672"},
    {"name": "مجلة المقدمة للدراسات الانسانية و الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/662"},
    {"name": "مجلة المقرى للدراسات اللغوية النظرية و التطبيقية", "url": "https://asjp.cerist.dz/en/PresentationRevue/477"},
    {"name": "مجلة المكتبات والمعلومات", "url": "https://asjp.cerist.dz/en/PresentationRevue/31"},
    {"name": "مجلة الممارسة الرياضية والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/626"},
    {"name": "مجلة المنارة للدراسات الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/584"},
    {"name": "مجلة المنتدى للدراسات والابحاث الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/428"},
    {"name": "مجلة المنظومة الرياضية", "url": "https://asjp.cerist.dz/en/PresentationRevue/372"},
    {"name": "مجلة المنهل", "url": "https://asjp.cerist.dz/en/PresentationRevue/507"},
    {"name": "مجلة المنهل الاقتصادي", "url": "https://asjp.cerist.dz/en/PresentationRevue/479"},
    {"name": "مجلة المواقف", "url": "https://asjp.cerist.dz/en/PresentationRevue/142"},
    {"name": "مجلة الموروث", "url": "https://asjp.cerist.dz/en/PresentationRevue/901"},
    {"name": "مجلة الموسوعة في القانون و العلوم السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/915"},
    {"name": "مجلة الميادين الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/613"},
    {"name": "مجلة الميدان للدراسات الرياضية و الإجتماعية و الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/444"},
    {"name": "مجلة الميزان", "url": "https://asjp.cerist.dz/en/PresentationRevue/521"},
    {"name": "مجلة المُؤَثَّل", "url": "https://asjp.cerist.dz/en/PresentationRevue/998"},
    {"name": "مجلة الناقد للدراسات السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/501"},
    {"name": "مجلة النبراس للدراسات القانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/470"},
    {"name": "مجلة النشاط البدني و الرياضي المجتمع و التربية و الصحة", "url": "https://asjp.cerist.dz/en/PresentationRevue/548"},
    {"name": "مجلة النص", "url": "https://asjp.cerist.dz/en/PresentationRevue/572"},
    {"name": "مجلة النقد الثقافي", "url": "https://asjp.cerist.dz/en/PresentationRevue/207"},
    {"name": "مجلة النمو الاقتصادي والمقاولاتية", "url": "https://asjp.cerist.dz/en/PresentationRevue/612"},
    {"name": "مجلة النوازل الفقهية والقانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/861"},
    {"name": "مجلة الواحات للبحوث و الدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/2"},
    {"name": "مجلة الونشريس للدراسات التاريخية", "url": "https://asjp.cerist.dz/en/PresentationRevue/820"},
    {"name": "مجلة امتياز للعلوم التربوية و التعليمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/810"},
    {"name": "مجلة ايكوفاين للدراسات الاقتصادية والمالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/683"},
    {"name": "مجلة ببليوفيليا لدراسات المكتبات والمعلومات", "url": "https://asjp.cerist.dz/en/PresentationRevue/627"},
    {"name": "مجلة بحوث الإدارة والاقتصاد", "url": "https://asjp.cerist.dz/en/PresentationRevue/615"},
    {"name": "مجلة بحوث الاقتصاد والمناجمنت", "url": "https://asjp.cerist.dz/en/PresentationRevue/655"},
    {"name": "مجلة بحوث في القانون والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/800"},
    {"name": "مجلة بحوث ودراسات في الميديا الجديدة", "url": "https://asjp.cerist.dz/en/PresentationRevue/778"},
    {"name": "مجلة تاريخ المغرب العربي", "url": "https://asjp.cerist.dz/en/PresentationRevue/227"},
    {"name": "مجلة تحولات", "url": "https://asjp.cerist.dz/en/PresentationRevue/502"},
    {"name": "مجلة تراث الزيبان", "url": "https://asjp.cerist.dz/en/PresentationRevue/963"},
    {"name": "مجلة تطوير العلوم الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/310"},
    {"name": "مجلة تعليميات", "url": "https://asjp.cerist.dz/en/PresentationRevue/624"},
    {"name": "مجلة تفوق في علوم وتقنيات النشاطات البدنية والرياضية", "url": "https://asjp.cerist.dz/en/PresentationRevue/208"},
    {"name": "مجلة جامعة الأمير عبد القادر للعلوم الإسلامية", "url": "https://asjp.cerist.dz/en/PresentationRevue/28"},
    {"name": "مجلة جامعة التكوين المتواصل", "url": "https://asjp.cerist.dz/en/PresentationRevue/594"},
    {"name": "مجلة جامعة وهران 2", "url": "https://asjp.cerist.dz/en/PresentationRevue/705"},
    {"name": "مجلة جودة الخدمة العمومية للدراسات السوسيولوجية والتنمية الإدارية", "url": "https://asjp.cerist.dz/en/PresentationRevue/816"},
    {"name": "مجلة حفريات المعرفة", "url": "https://asjp.cerist.dz/en/PresentationRevue/909"},
    {"name": "مجلة حقائق للدراسات النفسية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/675"},
    {"name": "مجلة حقوق الإنسان والحريات العامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/535"},
    {"name": "مجلة حقول معرفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/687"},
    {"name": "مجلة دائرة البحوث و الدراسات القانونية و السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/693"},
    {"name": "مجلة دراسات إنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/798"},
    {"name": "مجلة دراسات اجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/751"},
    {"name": "مجلة دراسات بيئية", "url": "https://asjp.cerist.dz/en/PresentationRevue/837"},
    {"name": "مجلة دراسات جبائية", "url": "https://asjp.cerist.dz/en/PresentationRevue/378"},
    {"name": "مجلة دراسات في الاقتصاد وإدارة الأعمال", "url": "https://asjp.cerist.dz/en/PresentationRevue/635"},
    {"name": "مجلة دراسات في المالية الإسلامية والتنمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/742"},
    {"name": "مجلة دراسات في الوظيفة العامة", "url": "https://asjp.cerist.dz/en/PresentationRevue/545"},
    {"name": "مجلة دراسات في سيكولوجية الانحراف", "url": "https://asjp.cerist.dz/en/PresentationRevue/704"},
    {"name": "مجلة دراسات في علم إجتماع المنظمات", "url": "https://asjp.cerist.dz/en/PresentationRevue/234"},
    {"name": "مجلة دراسات في علم النفس الإجرام، الأسرة والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/1000"},
    {"name": "مجلة دراسات في علم نفس الصحة", "url": "https://asjp.cerist.dz/en/PresentationRevue/739"},
    {"name": "مجلة دراسات مالية محاسبية وجبائية", "url": "https://asjp.cerist.dz/en/PresentationRevue/940"},
    {"name": "مجلة دراسات متقدمة في المالية والمحاسبة", "url": "https://asjp.cerist.dz/en/PresentationRevue/489"},
    {"name": "مجلة دراسات نفسية وتربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/339"},
    {"name": "مجلة دراسات وأبحاث اقتصادية في الطاقات المتجددة", "url": "https://asjp.cerist.dz/en/PresentationRevue/466"},
    {"name": "مجلة درلسات التنمية الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/777"},
    {"name": "مجلة دفاتر اقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/374"},
    {"name": "مجلة دفاتر الحقوق و العلوم السياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/865"},
    {"name": "مجلة رؤى اقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/126"},
    {"name": "مجلة رؤى مستقبلية للدراسات الاجتماعية والإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/1017"},
    {"name": "مجلة رصين في الأنشطة الرياضية و علوم الحركة", "url": "https://asjp.cerist.dz/en/PresentationRevue/743"},
    {"name": "مجلة رقمنة للدراسات الإعلامية والاتصالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/814"},
    {"name": "مجلة روافد للبحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/806"},
    {"name": "مجلة روافد للدراسات و الأبحاث العلمية في العلوم الاجتماعية والإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/539"},
    {"name": "مجلة روافد للدراسات والابحاث في علوم الرياضة", "url": "https://asjp.cerist.dz/en/PresentationRevue/788"},
    {"name": "مجلة سوسيولوجيا", "url": "https://asjp.cerist.dz/en/PresentationRevue/432"},
    {"name": "مجلة سيفار الدولية للدراسات التسويقية", "url": "https://asjp.cerist.dz/en/PresentationRevue/1023"},
    {"name": "مجلة سيميائيات", "url": "https://asjp.cerist.dz/en/PresentationRevue/168"},
    {"name": "مجلة شروح", "url": "https://asjp.cerist.dz/en/PresentationRevue/883"},
    {"name": "مجلة صوت القانون", "url": "https://asjp.cerist.dz/en/PresentationRevue/268"},
    {"name": "مجلة ضياء للبحوث النفسية والتربوية", "url": "https://asjp.cerist.dz/en/PresentationRevue/758"},
    {"name": "مجلة ضياء للدراسات القانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/722"},
    {"name": "مجلة طبنـــة للدراسات العلمية الأكاديمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/620"},
    {"name": "مجلة طلائع اللغة وبدائع الأدب", "url": "https://asjp.cerist.dz/en/PresentationRevue/805"},
    {"name": "مجلة عصور الجديدة", "url": "https://asjp.cerist.dz/en/PresentationRevue/178"},
    {"name": "مجلة علوم الإنسان والمجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/116"},
    {"name": "مجلة علوم التربية للتوجيه والإرشاد", "url": "https://asjp.cerist.dz/en/PresentationRevue/995"},
    {"name": "مجلة علوم الرياضة", "url": "https://asjp.cerist.dz/en/PresentationRevue/856"},
    {"name": "مجلة علوم الرياضة والتدريب", "url": "https://asjp.cerist.dz/en/PresentationRevue/369"},
    {"name": "مجلة علوم اللسان", "url": "https://asjp.cerist.dz/en/PresentationRevue/302"},
    {"name": "مجلة علوم اللغة العربية وآدابها", "url": "https://asjp.cerist.dz/en/PresentationRevue/130"},
    {"name": "مجلة علوم وتقنيات النشاط البدني الرياضي", "url": "https://asjp.cerist.dz/en/PresentationRevue/260"},
    {"name": "مجلة علوم وتقنيات النشاط البدني الرياضي", "url": "https://asjp.cerist.dz/en/PresentationRevue/555"},
    {"name": "مجلة علوم وتقنيات النشاطات البدنية والرياضية", "url": "https://asjp.cerist.dz/en/PresentationRevue/700"},
    {"name": "مجلة فصوص الادب والمعارف", "url": "https://asjp.cerist.dz/en/PresentationRevue/787"},
    {"name": "مجلة قانون العمل و التشغيل", "url": "https://asjp.cerist.dz/en/PresentationRevue/529"},
    {"name": "مجلة قبس للدراسات الإنسانية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/482"},
    {"name": "مجلة قضايا اقتصادية ومالية ومحاسبية", "url": "https://asjp.cerist.dz/en/PresentationRevue/957"},
    {"name": "مجلة قضايا فقهية واقتصادية معاصر", "url": "https://asjp.cerist.dz/en/PresentationRevue/818"},
    {"name": "مجلة قضايا معرفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/599"},
    {"name": "مجلة كفاية للغة والأدب", "url": "https://asjp.cerist.dz/en/PresentationRevue/919"},
    {"name": "مجلة كلية الآداب و العلوم الإنسانية و الإجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/108"},
    {"name": "مجلة كلية الآداب واللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/70"},
    {"name": "مجلة كلية الآداب واللغات", "url": "https://asjp.cerist.dz/en/PresentationRevue/94"},
    {"name": "مجلة مالك بن نبي للبحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/789"},
    {"name": "مجلة مالية ومحاسبة الشركات", "url": "https://asjp.cerist.dz/en/PresentationRevue/829"},
    {"name": "مجلة متيجة للدراسات الإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/867"},
    {"name": "مجلة مجتمع تربية عمل", "url": "https://asjp.cerist.dz/en/PresentationRevue/414"},
    {"name": "مجلة مخبر علوم الأداء الحركي والتدخلات البيداغوجية", "url": "https://asjp.cerist.dz/en/PresentationRevue/767"},
    {"name": "مجلة مدارات اجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/712"},
    {"name": "مجلة مدارات تاريخية", "url": "https://asjp.cerist.dz/en/PresentationRevue/654"},
    {"name": "مجلة مدينة ومجتمع", "url": "https://asjp.cerist.dz/en/PresentationRevue/776"},
    {"name": "مجلة مرافئ للدراسات السياسية والقانونية", "url": "https://asjp.cerist.dz/en/PresentationRevue/887"},
    {"name": "مجلة مشكلات الحضارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/283"},
    {"name": "مجلة معارف للعلوم القانونية والاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/676"},
    {"name": "مجلة معالم للدراسات الاعلامية و الاتصالية", "url": "https://asjp.cerist.dz/en/PresentationRevue/748"},
    {"name": "مجلة معهد العلوم الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/258"},
    {"name": "مجلة مفاهيم", "url": "https://asjp.cerist.dz/en/PresentationRevue/430"},
    {"name": "مجلة منارات لدراسات العلوم الاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/685"},
    {"name": "مجلة منبر التراث الأثري", "url": "https://asjp.cerist.dz/en/PresentationRevue/402"},
    {"name": "مجلة ميلاف للبحوث والدراسات", "url": "https://asjp.cerist.dz/en/PresentationRevue/89"},
    {"name": "مجلة مينا للدراسات الإقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/619"},
    {"name": "مجلة نازجر للدراسات النفسية و الاجتماعية.", "url": "https://asjp.cerist.dz/en/PresentationRevue/1025"},
    {"name": "مجلة نماء للإقتصاد والتجارة", "url": "https://asjp.cerist.dz/en/PresentationRevue/465"},
    {"name": "مجلة نور للدراسات الاقتصادية", "url": "https://asjp.cerist.dz/en/PresentationRevue/245"},
    {"name": "مجلة نوميروس الأكاديمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/609"},
    {"name": "مجلة هيرودوت للعلوم الإنسانية والاجتماعية", "url": "https://asjp.cerist.dz/en/PresentationRevue/686"},
    {"name": "مجلــة الأوراس لعلوم الرياضة", "url": "https://asjp.cerist.dz/en/PresentationRevue/935"},
    {"name": "مجلّة المحمديّة للدّراسات والبحوث", "url": "https://asjp.cerist.dz/en/PresentationRevue/1014"},
    {"name": "محاورات في الأدب والنقد", "url": "https://asjp.cerist.dz/en/PresentationRevue/825"},
    {"name": "مدار", "url": "https://asjp.cerist.dz/en/PresentationRevue/938"},
    {"name": "مدارات سياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/429"},
    {"name": "مدارات في اللغة والأدب", "url": "https://asjp.cerist.dz/en/PresentationRevue/663"},
    {"name": "مدارات للعلوم الإجتماعية والإنسانية", "url": "https://asjp.cerist.dz/en/PresentationRevue/694"},
    {"name": "مصداقية", "url": "https://asjp.cerist.dz/en/PresentationRevue/596"},
    {"name": "معارف", "url": "https://asjp.cerist.dz/en/PresentationRevue/270"},
    {"name": "معالم", "url": "https://asjp.cerist.dz/en/PresentationRevue/237"},
    {"name": "معالم للدراسات القانونية والسياسية", "url": "https://asjp.cerist.dz/en/PresentationRevue/520"},
    {"name": "مقابسات في اللغة والأدب", "url": "https://asjp.cerist.dz/en/PresentationRevue/802"},
    {"name": "مقاربات", "url": "https://asjp.cerist.dz/en/PresentationRevue/321"},
    {"name": "مقاربات فلسفية", "url": "https://asjp.cerist.dz/en/PresentationRevue/231"},
    {"name": "مقاربات في التعليمية", "url": "https://asjp.cerist.dz/en/PresentationRevue/677"},
    {"name": "مقاليد", "url": "https://asjp.cerist.dz/en/PresentationRevue/129"},
    {"name": "مقامات للدراسات اللسانية و الأدبية و النقدية", "url": "https://asjp.cerist.dz/en/PresentationRevue/697"},
    {"name": "مقدمات", "url": "https://asjp.cerist.dz/en/PresentationRevue/562"},
    {"name": "منيرفا", "url": "https://asjp.cerist.dz/en/PresentationRevue/201"},
    {"name": "موازين", "url": "https://asjp.cerist.dz/en/PresentationRevue/715"},
    {"name": "نتائج الفكر", "url": "https://asjp.cerist.dz/en/PresentationRevue/567"},
    {"name": "نفسانيات و أنام", "url": "https://asjp.cerist.dz/en/PresentationRevue/220"}
]

DOMAINES_KEYWORDS = {
    "Sciences exactes et naturelles": ["mathématique", "physique", "chimie", "biologie", "astronomie"],
    "Sciences de la vie": ["médecine", "pharmacie", "vétérinaire", "santé", "biochimie"],
    "Sciences de la terre": ["géologie", "géographie", "environnement", "hydraulique"],
    "Sciences de l'ingénieur": ["génie", "électronique", "mécanique", "informatique", "technologie"],
    "Sciences humaines": ["histoire", "philosophie", "archéologie", "patrimoine"],
    "Sciences sociales": ["sociologie", "psychologie", "anthropologie", "démographie"],
    "Droit et sciences politiques": ["droit", "juridique", "sciences politiques"],
    "Économie et gestion": ["économie", "gestion", "finance", "comptabilité", "management"],
    "Lettres et langues": ["littérature", "linguistique", "langue", "traduction", "lettres"],
    "Sciences islamiques": ["islamique", "fiqh", "charia", "coran", "hadith"],
    "Arts et architecture": ["arts", "architecture", "urbanisme", "design"],
    "Sciences de l'éducation": ["éducation", "pédagogie", "didactique", "formation"],
}

APPEL_KEYWORDS = [
    "appel à soumission", "appel à contribution", "call for paper",
    "call for papers", "soumettre", "soumission en cours",
    "numéro en cours", "accepte les soumissions", "dépôt des articles",
    "submit", "submission", "appel à articles",
]

MOIS_FR = {
    "janvier": 1, "février": 2, "mars": 3, "avril": 4,
    "mai": 5, "juin": 6, "juillet": 7, "août": 8,
    "septembre": 9, "octobre": 10, "novembre": 11, "décembre": 12,
}


def detect_domaine(texte: str) -> str:
    texte = texte.lower()
    for domaine, keywords in DOMAINES_KEYWORDS.items():
        if any(kw in texte for kw in keywords):
            return domaine
    return "Autre"


def extract_date(texte: str) -> Optional[date]:
    m = re.search(r"(\d{1,2})[/-](\d{1,2})[/-](\d{4})", texte)
    if m:
        try:
            d, mo, y = int(m.group(1)), int(m.group(2)), int(m.group(3))
            if 2024 <= y <= 2028 and 1 <= mo <= 12 and 1 <= d <= 31:
                return date(y, mo, d)
        except Exception:
            pass

    m = re.search(
        r"(\d{1,2})\s+(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)\s+(\d{4})",
        texte.lower()
    )
    if m:
        try:
            return date(int(m.group(3)), MOIS_FR[m.group(2)], int(m.group(1)))
        except Exception:
            pass

    return None


class ASJPScraper(BaseScraper):
    site_name = "ASJP"
    base_url = "https://asjp.cerist.dz"
    timeout = 20

    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            "User-Agent": "Mozilla/5.0 (compatible; UnivDZBot/1.0)"
        })

    def fetch(self, url: str):
        try:
            resp = self.session.get(url, timeout=self.timeout, verify=False)
            resp.raise_for_status()
            resp.encoding = resp.apparent_encoding
            return BeautifulSoup(resp.text, "html.parser")
        except Exception as e:
            logger.warning(f"[ASJP] Erreur fetch {url}: {e}")
            return None

    def get_calls_for_papers(self, journal: Dict) -> Optional[Dict]:
        soup = self.fetch(journal["url"])
        if not soup:
            return None

        page_text = soup.get_text(separator=" ").lower()

        has_appel = any(kw in page_text for kw in APPEL_KEYWORDS)
        call_links = soup.find_all("a", href=re.compile(r"callForPapers|Appel", re.IGNORECASE))
        if call_links:
            has_appel = True

        if not has_appel:
            return None

        nom = journal["name"]
        if not nom:
            h = soup.find("h1") or soup.find("h2")
            nom = h.get_text(strip=True) if h else "Revue sans nom"

        description = ""
        for cls in ["description", "about", "resume", "presentation"]:
            tag = soup.find(class_=re.compile(cls, re.I))
            if tag:
                description = tag.get_text(strip=True)[:500]
                break

        universite = ""
        m = re.search(r"(université[^,\n]{5,60}|univ\.[^,\n]{5,40})", page_text, re.I)
        if m:
            universite = m.group(0).strip()[:200]

        date_limite = extract_date(page_text)

        if date_limite and date_limite < date.today():
            return None

        return {
            "nom": nom[:500],
            "domaine": detect_domaine(nom + " " + description),
            "description": description,
            "universite": universite,
            "lien_asjp": journal["url"],
            "lien_officiel": journal["url"],
            "date_limite": date_limite,
            "statut_appel": "ouvert",
            "source": "ASJP",
        }

    def scrape(self) -> List[Dict]:
        revues = []

        for i, journal in enumerate(REVUES_ASJP[:20]):
            try:
                result = self.get_calls_for_papers(journal)
                if result:
                    revues.append(result)
                    logger.info(f"[ASJP] ✅ {result['nom'][:50]}")
                if i % 5 == 0:
                    time.sleep(1)
            except Exception as e:
                logger.error(f"[ASJP] Erreur {journal['url']}: {e}")

        logger.info(f"[ASJP] {len(revues)} revues avec appel ouvert")
        return revues

    def run_revues(self, app) -> int:
        from app import db
        from app.models.event import Revue
        from slugify import slugify

        count = 0

        with app.app_context():
            for raw in self.scrape():
                try:
                    if Revue.query.filter_by(lien_asjp=raw.get("lien_asjp")).first():
                        continue

                    base_slug = slugify(raw["nom"][:80], separator="-")
                    slug = base_slug
                    counter = 1

                    while Revue.query.filter_by(slug=slug).first():
                        slug = f"{base_slug}-{counter}"
                        counter += 1

                    revue = Revue(
                        nom=raw["nom"],
                        domaine=raw.get("domaine", "Autre"),
                        description=raw.get("description", ""),
                        universite=raw.get("universite", ""),
                        lien_asjp=raw.get("lien_asjp", ""),
                        lien_officiel=raw.get("lien_officiel", ""),
                        date_limite=raw.get("date_limite"),
                        statut_appel="ouvert",
                        source="ASJP",
                        date_collecte=datetime.utcnow(),
                        statut="a_verifier",
                        slug=slug,
                    )

                    db.session.add(revue)
                    count += 1

                except Exception as e:
                    logger.error(f"[ASJP] Erreur sauvegarde: {e}")
                    db.session.rollback()

            db.session.commit()

        return count